### ISSUE TITLE
Explore type annotations

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/python-pachyderm#117]
Explore adding type annotations to the client library. It's not clear if this would work well, (especially since so much of the code is autogenerated by gRPC/protobufs) but worth a go.

**Comment by ysimonson** [comment]
The autogenerated code creates _way_ too much noise. It looks like [mypy-protobuf](https://github.com/dropbox/mypy-protobuf/) could help with the protobuf code, but it [doesn't support annotating the gRPC code](https://github.com/dropbox/mypy-protobuf/issues/46).

**Comment by gabrielgrant** [comment]
Looks like there is an implementation here: https://github.com/samuela/grpc-polyglot

Any interest in giving that a shot?

**Comment by ysimonson** [comment]
I don't think it's stable enough yet for us to rely on it
