### ISSUE TITLE
Support backups

### ISSUE THREAD

**Issue by cfga** [pachyderm/python-pachyderm#125]
Expose extract and restore

**Comment by ysimonson** [comment]
We presently need to ignore admin-related protos because protoc generates invalid python code with it, due to package naming. There's some WIP to fix that.

**Comment by ysimonson** [comment]
In progress under https://github.com/pachyderm/pachyderm/pull/4072

**Comment by ysimonson** [comment]
Admin protos now imported (https://github.com/pachyderm/python-pachyderm/pull/127), this is unblocked
