### ISSUE TITLE
Broken docs links

### ISSUE THREAD

**Issue by gpkc** [pachyderm/python-pachyderm#130]
The links for the submodules on the documentation (https://pachyderm.github.io/python-pachyderm/python_pachyderm) are broken:
```
python_pachyderm.pfs_client
python_pachyderm.pps_client
python_pachyderm.util
```

They are pointing to `.m.html` addresses. If you remove the `.m`, it works.

**Comment by ysimonson** [comment]
Ah, I rebuilt with a buggy version of pdoc. Will fix shortly.
