### ISSUE TITLE
list_job() future not returning

### ISSUE THREAD

**Issue by Gezzellig** [pachyderm/python-pachyderm#132]
The futures provided by the PpsClient concerning jobs do not return.

python-pachyderm version: 1.9.4
pachyd version: 1.9.7

Code:
```python
import python_pachyderm

pps_client = python_pachyderm.PpsClient(host="***", port=30650)
pipes = pps_client.list_pipeline() #Show that it is properly connected
print("pipes: {}".format(pipes))
jobs = pps_client.list_job()
print("jobs: {}".format(jobs))
print("type: {}".format(type(jobs)))
print("result: {}".format(jobs.result())) #Future never returns and therefore Finished is not printed
print("Finished")
```

Output:
```
pipes: pipeline_info {
  pipeline {
    ................#not showing the rest, but that it outputs verifies that the connection to pachyderm works
jobs: <_Rendezvous object of in-flight RPC>
type: <class 'grpc._channel._Rendezvous'>
```
If more information is required please let me know.

**Comment by ysimonson** [comment]
I'm not managing to repro this issue, so my initial suspicion is that something with the cluster itself is making it unresponsive to job listing. What happens if you call `pachctl list job`?

**Comment by Gezzellig** [comment]
Thanks for the quick response,
`pachctl list job --raw --no-pager` returns the following:

```
pipes: pipeline_info {
  pipeline {
    name: "visualize"
  }
  transform {
    image: "***" #Anomymised
    cmd: "/bin/bash"
    stdin: "mkdir -p /pfs/out/1; python ./bin/main.py /pfs/visualize_conf/1/visualize_conf.json"
    image_pull_secrets: "myregistrykey"
    image_pull_secrets: "modelketenregistrykey"
  }
  created_at {
    seconds: 1570605769
    nanos: 63816188
  }
  state: PIPELINE_RUNNING
  version: 1
  output_branch: "master"
  resource_requests {
    memory: "64M"
  } ...............
```

pachctl is also able too list jobs properly.
Therefore my suspicion is that the problem lays with the python client

**Comment by ysimonson** [comment]
Ah! I managed to repro - before I didn't actually have any jobs or pipelines running, but once I did, the example you posted does indeed block. But to be honest, I'm not sure if this is due to a weirdness with this library, or with the gRPC python library, or with the pachyderm server, because while `jobs.result()` blocks, you can still coerce it to a list or iterate over the results fine. e.g. this works:

```
import python_pachyderm

pps_client = python_pachyderm.PpsClient(host="***", port=30650)
pipes = pps_client.list_pipeline() #Show that it is properly connected
print("pipes: {}".format(pipes))
jobs = pps_client.list_job()
print("jobs: {}".format(jobs))
print("type: {}".format(type(jobs)))
print("result: {}".format(list(jobs)))
print("Finished")
```

**Comment by Gezzellig** [comment]
Thanks this also works for me!
I saw a future, so assumed that I first needed to "wait" for the future to resolve.
I will use your implementation
