### ISSUE TITLE
DatumState missing enum value 3=STARTING

### ISSUE THREAD

**Issue by williballenthin** [pachyderm/python-pachyderm#15]
`DatumState` is missing the enum value 3 (`STARTING`). The current definition of `DatumState` look like this:

```
enum DatumState {
    FAILED = 0;
    SUCCESS = 1;
    SKIPPED = 2;
    STARTING = 3;
}
```

Perhaps `pps_pb2.py` needs to be regenerated.

**Comment by williballenthin** [comment]
`DatumInfo` also missing field `data`.

**Comment by ysimonson** [comment]
Protobufs have been regenerated, so this should be fixed
