### ISSUE TITLE
support a way to check pachyderm grpc client connection is active

### ISSUE THREAD

**Issue by amoallim15** [pachyderm/python-pachyderm#158]
`client = python_pachyderm.Client(host=PACHY_END_POINT, port=PACHY_PORT)`
`client.ping()`
raise grpc exception if not connected..

for an example:
https://github.com/andymccurdy/redis-py/blob/29f4aa43aec50ae0e28df4d3fadfcb17cebe2a2f/redis/client.py#L1104

**Comment by ysimonson** [comment]
This is supported as of today! Try client.health().

**Comment by amoallim15** [comment]
u r fantastic))) 
I will using client.list_repo() in version 2.1.0 ^^
