### ISSUE TITLE
Authentication method does not work

### ISSUE THREAD

**Issue by xxmarl** [pachyderm/python-pachyderm#164]
Hi,

I'm trying to use pachyderm python client with pachyderm service deployed on cluster (with port forwarding). I guess from other issues raised (there is lack of documentation in that topic), that I should set up $PACH_PYTHON_AUTH_TOKEN with my github authentication token. After that I still encounter the following error when trying to use python client. Please note that I am able to use pachctl with the same token without any problems.

````
 import python_pachyderm
client = python_pachyderm.Client()
client.list_repo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nlmluk/.local/lib/python3.7/site-packages/python_pachyderm/mixin/pfs.py", line 49, in list_repo
    return self._req(Service.PFS, "ListRepo").repo_info
  File "/home/nlmluk/.local/lib/python3.7/site-packages/python_pachyderm/client.py", line 170, in _req
    return grpc_method(req, metadata=self._metadata)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 604, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/dist-packages/grpc/_channel.py", line 506, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "error getting access level for "png2numpy_test": provided auth token is corrupted or has expired (try logging in again)"
        debug_error_string = "{"created":"@1576489669.430978200","description":"Error received from peer ipv4:127.0.0.1:30650","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"error getting access level for "png2numpy_test": provided auth token is corrupted or has expired (try logging in again)","grpc_status":2}"
```

**Comment by ysimonson** [comment]
A couple of things:

1) In order to be more explicit, it'd be better to pass the auth token in as a parameter to the client. See `auth_token` in `__init__` here: https://pachyderm.github.io/python-pachyderm/python_pachyderm.m.html#python_pachyderm.Client

2) Most likely the cause of the error you're seeing is that you're not passing in the full auth token value in. Auth tokens have a prefix like `github:` - make sure to include that prefix.

**Comment by xxmarl** [comment]
Hi @ysimonson , thanks for your suggestions. My mistake was that I was trying to use user github authentication token (same as I use to access dashboard or with `pachctl auth login`) while it expects a token generated with `pachctl auth get-auth-token`. It would be nice to mention it somewhere to avoid confusion.
