### ISSUE TITLE
Add a flag to pass a .json or .yaml file to create_pipeline method

### ISSUE THREAD

**Issue by svekars** [pachyderm/python-pachyderm#165]
Currently, you can only pass pipeline parameters by specifying them inline in your Python code for both the `create_pipeline` method and the `create_python_pipeline` function. It would be nice to have a parameter called `file` or similar to pass a complete pipeline spec. This improvement brings the following benefits:

- Decouples the pipeline spec from the pipeline code, which simplifies updating the pipeline.
- Enables users to adopt existing pipeline examples without modifying them for python-pachyderm/JupyterHub.
- Eliminates the need to create additional examples for pachyderm/JupyterHub.

cc: @JoeyZwicker @ysimonson

**Comment by ysimonson** [comment]
Related:

- https://github.com/pachyderm/python-pachyderm/issues/7
- https://github.com/pachyderm/python-pachyderm/issues/19
- https://github.com/pachyderm/python-pachyderm/issues/21

This function should do the trick: https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.json_format-module.html#Parse
