### ISSUE TITLE
Allow customization of the input/output directory for `SpoutManager`

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/python-pachyderm#184]
This will make it easier to test `SpoutManager`s in tests running outside of an actual pipeline

gz#22

**Comment by pappasilenus** [comment]
Agent comment from John Karabaic in <a href='https://pachyderm.zendesk.com/agent/tickets/22'>Zendesk ticket #22</a>:  
  
Note that the specific user request is to customize the output of a spout for testing.

**Comment by pappasilenus** [comment]
Agent comment from John Karabaic in <a href='https://pachyderm.zendesk.com/agent/tickets/22'>Zendesk ticket #22</a>:<br><br>This feature was recently merged into master:

https://github.com/pachyderm/python-pachyderm/pull/188

Take a look and give us some feedback!
