### ISSUE TITLE
PpsClient.create_pipeline() requires all fields of a pipeline spec

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/python-pachyderm#21]
It seems this method requires all the top-level fields of a pipeline spec be passed in as individual function arguments, rather than accepting a single `pipeline_spec` 

specific error:

```
Traceback (most recent call last):
  File "pipeline_creator.py", line 52, in <module>
    main()
  File "pipeline_creator.py", line 39, in main
    client.create_pipeline(spec)
TypeError: create_pipeline() missing 15 required positional arguments: 'transform', 'parallelism_spec', 'inputs', 'egress', 'update', 'output_branch', 'scale_down_threshold', 'resource_spec', 'input', 'description', 'incremental', 'cache_size', 'enable_stats', 'reprocess', and 'batch'
```

**Comment by Snapple49** [comment]
Any news on this? I would also like to be able to use a single specification, I tried looking into the protobuf to solve it for myself but I have no clue how that stuff works, or even what kind of data the command expects for each argument

**Comment by ysimonson** [comment]
No news on this yet, but yeah 15 arguments is...excessive. Maybe we can convince @christianladron to open a PR :)

**Comment by ysimonson** [comment]
Actually not sure if that repo has since been changed, but it looks like its `create_pipeline` still takes 15 arguments?

**Comment by christianladron** [comment]
I think we can change all the functions in `pfs_client.py` and `pps_client.py` to use only 1 argument, a dictionary, and send this dictionary as keyword arguments to the protobuf generated methods using `**`

**Comment by ysimonson** [comment]
The latest release:
* syncs `create_pipeline` up with the current protobufs
* makes all fields other than the pipeline name optional
* changes the first argument to be a string rather than a `Pipeline` object, since the name is the only field needed

See `examples/opencv.py` for a demo

**Comment by Snapple49** [comment]
Awesome, thanks for updating! I'll have a go at it later and test it in actual use, but looking at the example I'm wondering if it is really necessary to make it use the proto constructors explicitly and not just accepting dictionaries and converting to proto behind the scenes? 

In the opencv example you create a pipeline like this:
```
pps_client.create_pipeline(
        "edges",
        transform=proto.Transform(cmd=["python3", "edges.py"], image="pachyderm/opencv"),
        input=proto.Input(pfs=proto.PFSInput(glob="/*", repo="images"))
)
```

Would it not feel more pythonic and natural to do something like this:
```
pps_client.create_pipeline(
        "edges",
        transform={"cmd" : ["python3", "edges.py"], image : "pachyderm/opencv"},
        input={"pfs" : {"glob" : "/*", "repo" : "images"}}
)
```

Maybe it is just me but since I work a lot with pipeline spec files in json, this would be more in line with that. It it is troublesome to write a dict to proto parser for this, I don't know. Either way, it's great to see work done to the python client, was waiting for this as the fork I mentioned above didn't solve my issues at all in the end

**Comment by ysimonson** [comment]
@Snapple49 I actually kinda feel like the former is more pythonic. Granted, protobuf objects aren't the most idiomatic python, but they are, to me, a step up from free-form dicts.

I could see this causing confusion, though, around knowing what protobuf objects are supposed to be used where, their arguments, etc. For example, what input are you supposed to use for the `parallelism_spec` argument to `create_pipeline`? It's not easy to find out at the moment, whereas, with free-form dicts, you can at least look to `pachctl` usage and [the docs](http://docs.pachyderm.io/en/latest/reference/pipeline_spec.html#parallelism-spec-optional) to figure it out.

I'm actively working on making this better. In a bunch of changes merged on master yesterday, the package structure has been reorganized and [API docs](https://htmlpreview.github.io/?https://github.com/pachyderm/python-pachyderm/blob/master/docs/python_pachyderm/index.html) have been improved. I'll mull on other improvements that could be made.

For what it's worth, my current process is to just look at the protobuf files and dig around the package in the repl to figure it out. This works, but is not a great process, as it requires too much prior experience in protobufs.

**Comment by christianladron** [comment]
@Snapple49 @ysimonson I made this function `create_pipeline_dict` thinking in the posibility of make a `json.load()` of a pipeline json file, but I don't know if this is useful given the new reate_pipeline`.
https://github.com/christianladron/python-pachyderm/blob/1dd67be5301aabf51329a3d8d38c95cd84f4e2c1/src/python_pachyderm/pps_client.py#L58

**Comment by ysimonson** [comment]
I haven't used it before, but protobufs also have a built-in methods for converting to/from JSON: https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.json_format-module

**Comment by Snapple49** [comment]
I'll have a look and update my experiences with it, it's also not too much trouble using it as it is. Thanks!
