### ISSUE TITLE
need exception handling in spout code

### ISSUE THREAD

**Issue by lukemarsden** [pachyderm/python-pachyderm#224]
What happens if, here:

https://github.com/pachyderm/python-pachyderm/blob/master/src/python_pachyderm/spout.py#L63

The consumer of the `with` clause raises an Exception?

Presumably, we'll break the next time we call `commit()`. We should handle that exception and still release the resource, like in the example:

https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager

**Comment by msteffen** [comment]
Fixed by https://github.com/pachyderm/python-pachyderm/pull/225
