### ISSUE TITLE
get_file   return "The requested range is not satisfiable "

### ISSUE THREAD

**Issue by goodskillprogramer** [pachyderm/python-pachyderm#226]
I use client.put_file_bytes to upload files to server . The file is about 10G . So i upload it part by part ,each  part is 500*1024*1024 . The file can be upload success . But when I download the file by client.get_file API, I cant set the offset_bytes to 500*1024*1024 or any value that is multiple of  500*1024*1024. The server return error "The requested range is not satisfiable".

**Comment by JoeyZwicker** [comment]
@goodskillprogramer Can you give us more details on what you did specifically to break up each part? Were each of those parts separate `client.put_file_bytes` calls and where they putting to the same file name of different one? If you want to copy the exact cmds you used, as well as the one that's erroring that might be easiest

**Comment by goodskillprogramer** [comment]
> @goodskillprogramer Can you give us more details on what you did specifically to break up each part? Were each of those parts separate `client.put_file_bytes` calls and where they putting to the same file name of different one? If you want to copy the exact cmds you used, as well as the one that's erroring that might be easiest

@JoeyZwicker Please see my code below. Error will return when I call pach.get_file('test_upload/master', "/test.csv",savepath,offset=500*1024*1024 )

`import logging
import python_pachyderm
import os
import shutil

log =logging.getLogger(__name__)

class PachydermHelper(object):
    upload_part_size = 500*1024*1024
    download_part_size = 110*1024*1024
    def __init__(self,host=None,port=None):
        self.client = python_pachyderm.Client(host=host,port=port)
        
    def put_file(self,repo,src_file,dst_file,branch=None,description=None):
        total_len = 0
        with open(src_file,'rb') as source:
            if description is None:
                description='put file to {}'.format(dst_file)    
            with self.client.commit(repo, branch,description=description) as c:  
                log.info('put_file {}@{}:{} commit ID {}'.format(repo,branch,src_file,c.id))
                while True:
                    content = source.read(PachydermHelper.upload_part_size)
                    if not content:
                        break   
                    log.info('start put_file part len {}'.format(len(content)))
                    self.client.put_file_bytes(c, dst_file, content)
                    total_len+=len(content)
                    log.info('finish put_file part len {} total {}'.format(len(content),total_len/(1024*1024)))
                    
    def get_file(self,commit,sourcepath,savepath,offset,size=0):
        """save it to a temp file."""
        with open(savepath, "wb") as dest_file:  
            log.debug('download file part offset {} szie {}'.format(offset/(1024*1024),size/(1024*1024)))
            source_file = self.client.get_file(commit, sourcepath,
                                                   offset_bytes=offset,
                                                   size_bytes=size)                    
            shutil.copyfileobj(source_file,dest_file)
        return savepath 
    
if __name__ =="__main__":
    
    host = '127.0.0.1'
    localfile = r'./test.csv' #file size is about 1G ,which will be updalod by two parts
    savepath = r'./test.csv.download'
    pach = PachydermHelper(host)
    pach.client.create_repo('test_upload')
    pach.client.create_branch('test_upload', 'master')
    pach.put_file('test_upload',localfile , "/test.csv", 'master')    
    pach.get_file('test_upload/master', "/test.csv",savepath,offset=500*1024*1024 )`

**Comment by jdoliner** [comment]
Could you show us what the file looks like with `pachctl inspect file` that will show us what the total size of the file is. You could also try getting it with `pachctl get file` to see if it's able to return all of the bytes that it claims to have.

**Comment by goodskillprogramer** [comment]
> Could you show us what the file looks like with `pachctl inspect file` that will show us what the total size of the file is. You could also try getting it with `pachctl get file` to see if it's able to return all of the bytes that it claims to have.
(1) 
pachctl inspect file test_upload@master:/test.csv --raw
{
  "file": {
    "commit": {
      "repo": {
        "name": "test_upload"
      },
      "id": "2e06daabed1f4479a567de204de9f794"
    },
    "path": "/test.csv"
  },
  "fileType": "FILE",
  "sizeBytes": "1090064657",
  "committed": "2020-09-24T06:29:26.304214075Z",
  "objects": [
    {
      "hash": "bfa3e800b6bb7fb898530975f428c2b14d8b6ae34872c49ce2dcbd5dcfbce8ac23f0454045c3f697c930f60537780abed75fffff331eac622f28bf7b5d0a8681"
    },
    {
      "hash": "01e06d447833d389a1abad672ca6965bfa8938aef1605b1f294577bcdaa9f10382869fce1b5bb8d23406664a1f8b005bfab51523fde1f43ba202076b458cc1ab"
    },
    {
      "hash": "22b34f60f761de4049dcd8cf6be6371b1d094006c71591b96f8d288aaa6ff8c668710d5b52a9a432f80be1d82e539e7792ddf8d1b9d815ba2d1a19a3395991aa"
    }
  ],
  "hash": "W7AzSe9IGLVC6FwXFc1Wo9+wr7a6foj33Eg7slokKWU="
}
(2) Yes,I can get the whole file with the same size.

**Comment by nitinjainsj** [comment]
@goodskillprogramer Thanks for the code that triggered this exact condition. We have a fix underway. Your workaround, for now, is the download offset does should not fall on the upload part boundary. In your example, if the upload part is set to 400MB, you should be able to successfully do getFile starting at offset 500MB.

**Comment by nitinjainsj** [comment]
Should be fixed in pach version after 1.11.4
