### ISSUE TITLE
New release of python-pachyderm on PyPI needed

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/python-pachyderm#233]
Creating this Issue to keep track of its life cycle.

Copying our Slack thread here for context: https://pachyderm.slack.com/archives/C0194T0MW1G/p1609712543235000?thread_ts=1609546589.212000&cid=C0194T0MW1G

In short: 
Today, the latest package of `python-pachyderm` available on PyPI is is the 6.0.0 https://pypi.org/project/python-pachyderm/#history released on July 30, 2020. 
Yet... the class method `new_from_config` has been pushed on GitHub on August 14, 2020. It is needed to connect a Client to pachd (i.e. Pass credentials).

We need a new release of python-pachyderm.

Side note: Please review and include the following Issue #231 
Side side note: There is a couple of lingering open PRs on that repo https://github.com/pachyderm/python-pachyderm/pulls

**Comment by actgardner** [comment]
We just released python_pachyderm 6.1.0 :)
