### ISSUE TITLE
Client.new_from_config() does not exist and should be removed from the docs

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/python-pachyderm#238]
The issue name says it all :)

**Comment by nadegepepin** [comment]
This relates to: https://github.com/pachyderm/python-pachyderm/issues/233

In short: 
Today, the latest package of python-pachyderm available on PyPI is is the 6.0.0 https://pypi.org/project/python-pachyderm/#history released on July 30, 2020.  
Yet... the class method `new_from_config` has been pushed on GitHub on August 14, 2020. It is needed to connect a Client to pachd (i.e. Pass credentials).
We need a new release of python-pachyderm.

**Comment by actgardner** [comment]
@RaananHadar We just released python_pachyderm 6.1.0, which includes `Client.new_from_config`. Try it out and let us know if you have any issues :)
