### ISSUE TITLE
Make `repo@commit:path` syntax work in the PFS mixin.

### ISSUE THREAD

**Issue by msteffen** [pachyderm/python-pachyderm#255]
Pachyderm adopted this syntax several releases ago, but python-pachyderm has not yet been updated to support it.

**Comment by albscui** [comment]
Do we want to change the existing behaviour from something like

```
source_file = client.get_file("montage/master", "/montage.png")
```

To

```
source_file = client.get_file("montage@master:/montage.png")
```

Or do we want to support both ways?

**Comment by jdoliner** [comment]
I like standardizing on `<repo>@<commit-or-branch>:<file>` to match pachctl.

**Comment by albscui** [comment]
After some discussion, @JimmyWhitaker and I decided that explicit arguments for `repo`, `commit/branch`, and `path` is a bit nicer from a Python programming perspective.

So instead of `get_file("repo@commit:path")`, our new API would be `get_file("repo", "commit", "path")`.

**Comment by msteffen** [comment]
@albscui That makes sense. If we do this, I think we should drop support for the `repo/commit` syntax: https://github.com/pachyderm/python-pachyderm/blob/9d60ea887a4eeaba45f68a0375ba2640ba48ed01/src/python_pachyderm/mixin/util.py#L7-L11.

For consistency, we might also want to change inspect_file, list_file, walk_file, glob_file, etc.

It might also be worth confirming with LP—I think they use python-pachyderm a bit differently than @JimmyWhitaker. At least, I think Jimmy has said he prefers not to use python-pachyderm interactively in notebooks (correct me if I'm wrong :slightly_smiling_face: ), but IIUC that's the main way LP uses it

**Comment by albscui** [comment]
closing this in favour of https://github.com/pachyderm/python-pachyderm/issues/287
