### ISSUE TITLE
Should we deprecate/remove `create-python-pipeline`?

### ISSUE THREAD

**Issue by msteffen** [pachyderm/python-pachyderm#275]
Per @nadegepepin: `create-python-pipeline` seems to be an ancestor of build pipelines: Does it still work with 1.x and will it work with 2.0?

**Comment by albscui** [comment]
`create_python_pipeline` uses Build Pipelines underneath. However, we are deprecating Build Pipelines as a whole. https://github.com/pachyderm/python-pachyderm/issues/288
