### ISSUE TITLE
Support putting individual files

### ISSUE THREAD

**Issue by msteffen** [pachyderm/python-pachyderm#293]
Currently, the python-pachyderm helper function for putting files, `put_files`, doesn't work if `source_path` is an individual file. This is because the implementation calls `os.walk`, which returns an empty list if its argument is a regular file (rather than a directory)

Since putting an individual file is by far the more common use of e.g. `pachctl put file`, we'd like to support that case in python as well. Thus, we'd like to make two changes:

1) call `os.stat` on the `source_path` passed to `put_files`, and if that argument is a regular file, just upload it directly
2) Add a function `put_file` that is similar to `put_files`, but requires its argument to be a regular file.

**Comment by smalyala** [comment]
Decided to consolidate new `put_file` functionality into already existing `put_files` because logic is very similar. Creating a new function seems unnecessary from a user perspective.
