### ISSUE TITLE
PPS: Question: Should `list_pipeline` include an optional parameter for `pipeline_name`?

### ISSUE THREAD

**Issue by echohack** [pachyderm/python-pachyderm#314]
Hello,

This morning I was looking at this method due to some customer questions, and it struck me as very weird that this optional parameter was added for `list_pipeline`. What exactly is this parameter doing? It seems like circular logic that you'd need to know the pipeline name before you got a list of all the pipelines (and that `inspect` should give you what you want once you know the pipeline name).

I also found it odd that this was NOT included in 6.x python-pachyderm, and instead was a bug(?) in the docstring. Is it possible that this was accidentally carried forward and doesn't actually match what the actual PPS API should be doing?

See also: #312

**Comment by smalyala** [comment]
You are correct, I'll be fixing this behavior.
