### ISSUE TITLE
`input` in pipeline info empty 

### ISSUE THREAD

**Issue by David-Development** [pachyderm/python-pachyderm#32]
When using `list_pipeline` or `inspect_pipeline`, the `input` attribute is always empty. 

```python
pps_client.list_pipeline()
pps_client.inspect_pipeline(pipeline.pipeline.name)
```

Output (single `input` repo in pipeline spec):
```
...
input {
}
...
```

Output (two `input` repos in pipeline spec (using cross)):
```
...
input {
   cross {
   }
   cross {
   }
}
...
```

I would like to be able to get some information about the input repos for the pipelines.

**Comment by ysimonson** [comment]
Does the latest from master fix this issue?

**Comment by David-Development** [comment]
@ysimonson Yes, it does! Thanks 👍
