### ISSUE TITLE
Client doesn't has a wait_commit method, opencv example

### ISSUE THREAD

**Issue by oosugi84** [pachyderm/python-pachyderm#332]
Maybe the example needs update?

python-pachyderm==6.3.2

**Comment by smalyala** [comment]
Hi, 

`wait_commit` is what the function will be called in the next major version 7.0. The equivalent in version 6.0 is `flush_commit`, which is used in the opencv example.

**Comment by msteffen** [comment]
Closing this issue, but feel free to re-open @oosugi84 if your issue hasn't been addressed.

Our next roadmap item is to move to a docs page that will let us serve docs for multiple versions of python-pachyderm simultaneously, hopefully avoiding this kind of ambiguity in the future. Thanks for reaching out!
