### ISSUE TITLE
`Client.get_file` silently ignores parameters

### ISSUE THREAD

**Issue by defiori** [pachyderm/python-pachyderm#410]
Starting in ` v7.2.1`, the `URL` and `offset` parameters to [`Client.get_file`](https://github.com/pachyderm/python-pachyderm/blob/v7.2.1/src/python_pachyderm/mixin/pfs.py#L887) are ignored, is this an intentional breaking change?

**Comment by bbonenfant** [comment]
This was not intentional. Thank you for the bug repot, we will get this fixed as soon as possible.

**Comment by bbonenfant** [comment]
This fix was released in version 7.3.3 of python-pachyderm
