### ISSUE TITLE
python-pachyderm 7.6.0 requires protobuf<4.0.0,>=3.17.1

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [pachyderm/python-pachyderm#443]
I'm trying to use `Pachyderm` with `dbt` and running afoul of `protobuf` pins.

The last release of `protobuf` in the 3.x series was Sept 2022.  `dbt-core 1.4.x` was released in that era.

Version 4.x of `protobuf` has been in the wild since May 2022, and its latest release was Feb 2024.  `dbt-core 1.5.x` and later all depend upon this version.  The latest version, released this month, is 1.7.13.

Version 5.x has been in the wild since March 2024.  `dbt-core` does not yet support that version.

Is there any prospect of releasing an updated version of `Pachyderm` that works with `protobuf 4.25.3`?

**Comment by MichaelTiemannOSC** [comment]
`dbt-core` has just been updated to 1.8.0 and brings with it many long-sought capabilities, particularly related to unit testing of data transformations.  I have read https://www.determined.ai/blog/community-update and hope that part of HPE's commitment to Pachyderm includes keeping up with dependencies more recent than 24 months ago.

**Comment by bbonenfant** [comment]
Apologies, we are about to archive this project as we are no longer maintaining it. Please transition to using the improved and fully supported [pachyderm-sdk](https://github.com/pachyderm/pachyderm/tree/master/python-sdk). If you have concerns about any dependency versions please raise the issue in that repo. Thank you.
