### ISSUE TITLE
Inconsistent (?) overwrite/append behaviour

### ISSUE THREAD

**Issue by cfga** [pachyderm/python-pachyderm#53]
In case of a commit with no branch specified, consequent writes overwrite data files completely, no matter even whether overwrite_index is passed or not. However, for commits going to a specific branch the default behaviour is _append_. A quick example to illustrate this:

```python
pfs_client.create_repo('test-repo-1')

    with pfs_client.commit('test-repo-1', 'mybranch') as c:
        pfs_client.put_file_bytes(c, 'file.dat', b'DATA')

    with pfs_client.commit('test-repo-1', 'mybranch') as c:
        pfs_client.put_file_bytes(c, 'file.dat', b'FOO')

    file = list(pfs_client.get_file('test-repo-1/{}'.format(c.id), 'file.dat'))
    print(file)
```

This outputs `[b'DATA', b'FOO']`. Now the same code but without the branch:

```python
pfs_client.create_repo('test-repo-1')

    with pfs_client.commit('test-repo-1') as c:
        pfs_client.put_file_bytes(c, 'file.dat', b'DATA')

    with pfs_client.commit('test-repo-1') as c:
        pfs_client.put_file_bytes(c, 'file.dat', b'FOO')

    file = list(pfs_client.get_file('test-repo-1/{}'.format(c.id), 'file.dat'))
    print(file)
```

This outputs just `[b'FOO']`.

This looks rather inconsistent.

**Comment by ysimonson** [comment]
In the first case, the two commits are related by both being on the `mybranch` branch. In the second case, there's no relationship between the two commits. You can think of the second case as making commits on two different detached heads in git.

**Comment by cfga** [comment]
Yes, just noticed that all the commits in the first case do not actually have parents.
