### ISSUE TITLE
Flush_commit not accepting any commit

### ISSUE THREAD

**Issue by ccotar** [pachyderm/python-pachyderm#57]
I am writing some pytests for each pipeline I create, and one requirement is to verify that the pipeline has the correct output in the output repo after the test runs.  I would like to do this verification by using `flush-commit` to block the test until the input commit produces all output commits in the output repo.

Here is some of my code:
```
# when
with pytest.pfs_client.commit(input_repo, 'master') as c:
    pytest.pfs_client.put_file_bytes(c, 'input.json', input_file.encode())

pytest.pfs_client.flush_commit([f'{c.repo.name}/{c.id}'])

# then
files = pytest.pfs_client.get_files(f'output-repo/master', '/', recursive=True)
assert len(files) == 66
```

The problem I'm having is at the `flush_commit` call.

The call says it can take a `Commit` object, that doesn't work.

It also shows in the `utils.py` file that from_commit takes strings (like the one I'm trying to create from the original commit) but this does not work either.
For this case, I get this error: `ValueError: Protocol message FlushCommitRequest has no "commit" field.`

Am I using this the correct way?

**Comment by ysimonson** [comment]
That looks like an error created by the protos the python client uses being out of sync with the protos that the pach cluster expects. What version of the client library and pach cluster are you using?

**Comment by ccotar** [comment]
```
COMPONENT           VERSION
pachctl             1.9.0rc1
pachd               1.9.0rc1
```

```
Name: python-pachyderm
Version: 1.8.6
```

**Comment by ccotar** [comment]
Just changed my pachyderm version back to 1.8.6 and redeployed locally, still getting the same errors

**Comment by ysimonson** [comment]
Got it, looks like a bug in the client. I'll PR a fix shortly.
