### ISSUE TITLE
create_repo hangs

### ISSUE THREAD

**Issue by jax79sg** [pachyderm/python-pachyderm#59]
`import python_pachyderm`
`client = python_pachyderm.PfsClient()`
`client.create_repo('voc2012')`

Pachyderm is installed and running on microk8s.
The execution simply hang at the last line above.
How can i print the logs of the statement?

**Comment by ysimonson** [comment]
Most likely this means some sort of connectivity issue with the cluster itself. Are you able to create the repo from the `pachctl` CLI?

**Comment by jax79sg** [comment]
I removed the MicroK8s and reinstalled with minikube. That seems to remove the problem.
