### ISSUE TITLE
Add way to convert CommitInfo object to dict

### ISSUE THREAD

**Issue by munsanje** [pachyderm/python-pachyderm#7]
Currently there appears to be no way to convert a CommitInfo object obtained via `client.list_commit` to something readily usable in Python such as a dictionary. It seems natural for there to be such a conversion.

**Comment by williballenthin** [comment]
@munsanje I've been using the following utility to do the conversion:

```
def protobuf_to_dict(obj):
    # ref: https://stackoverflow.com/a/39685021/87207
    return json.loads(MessageToJson(obj))
```

**Comment by ysimonson** [comment]
Returning a dict would definitely be an ergonomic improvement, but this prevents possibly unnecessary conversions between protobufs and more native python objects, and protobufs provide a fairly simple way to convert to dicts (or JSON, as shown above) if necessary.
